/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Outcome = IDL.Variant({
  'win' : IDL.Null,
  'pending' : IDL.Null,
  'loss' : IDL.Null,
});
export const Signal = IDL.Record({
  'id' : IDL.Nat,
  'rsi' : IDL.Nat,
  'direction' : Direction,
  'asset' : IDL.Text,
  'macdValue' : IDL.Float64,
  'timestamp' : Time,
  'expiryMinutes' : IDL.Nat,
  'confidence' : IDL.Nat,
  'stochasticD' : IDL.Nat,
  'stochasticK' : IDL.Nat,
  'outcome' : Outcome,
  'macdSignalLine' : IDL.Float64,
});
export const AssetStats = IDL.Record({
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'winRate' : IDL.Nat,
  'totalSignals' : IDL.Nat,
});
export const Analytics = IDL.Record({
  'lossCount' : IDL.Nat,
  'perAssetBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, AssetStats)),
  'winCount' : IDL.Nat,
  'winRate' : IDL.Nat,
  'totalSignals' : IDL.Nat,
});
export const BacktestResult = IDL.Record({
  'totalTrades' : IDL.Nat,
  'endDate' : Time,
  'asset' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'winRate' : IDL.Nat,
  'maxDrawdown' : IDL.Float64,
  'avgProfit' : IDL.Float64,
  'startDate' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const IndicatorConfig = IDL.Record({
  'rsiPeriod' : IDL.Nat,
  'timeframe' : IDL.Text,
  'stochasticOverbought' : IDL.Nat,
  'stochasticDPeriod' : IDL.Nat,
  'macdLongPeriod' : IDL.Nat,
  'rsiOversold' : IDL.Nat,
  'stochasticKPeriod' : IDL.Nat,
  'rsiOverbought' : IDL.Nat,
  'stochasticOversold' : IDL.Nat,
  'macdSignalPeriod' : IDL.Nat,
  'minConfidence' : IDL.Nat,
  'macdShortPeriod' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSignal' : IDL.Func(
      [
        IDL.Text,
        Direction,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getBacktestResults' : IDL.Func([], [IDL.Vec(BacktestResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailySignalCounts' : IDL.Func([], [IDL.Vec(DailyCount)], ['query']),
  'getIndicatorConfig' : IDL.Func([], [IDL.Opt(IndicatorConfig)], ['query']),
  'getSignalsByAsset' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveBacktestResult' : IDL.Func([BacktestResult], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveIndicatorConfig' : IDL.Func([IndicatorConfig], [], []),
  'updateSignalOutcome' : IDL.Func([IDL.Nat, Outcome], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Outcome = IDL.Variant({
    'win' : IDL.Null,
    'pending' : IDL.Null,
    'loss' : IDL.Null,
  });
  const Signal = IDL.Record({
    'id' : IDL.Nat,
    'rsi' : IDL.Nat,
    'direction' : Direction,
    'asset' : IDL.Text,
    'macdValue' : IDL.Float64,
    'timestamp' : Time,
    'expiryMinutes' : IDL.Nat,
    'confidence' : IDL.Nat,
    'stochasticD' : IDL.Nat,
    'stochasticK' : IDL.Nat,
    'outcome' : Outcome,
    'macdSignalLine' : IDL.Float64,
  });
  const AssetStats = IDL.Record({
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'winRate' : IDL.Nat,
    'totalSignals' : IDL.Nat,
  });
  const Analytics = IDL.Record({
    'lossCount' : IDL.Nat,
    'perAssetBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, AssetStats)),
    'winCount' : IDL.Nat,
    'winRate' : IDL.Nat,
    'totalSignals' : IDL.Nat,
  });
  const BacktestResult = IDL.Record({
    'totalTrades' : IDL.Nat,
    'endDate' : Time,
    'asset' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'winRate' : IDL.Nat,
    'maxDrawdown' : IDL.Float64,
    'avgProfit' : IDL.Float64,
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const IndicatorConfig = IDL.Record({
    'rsiPeriod' : IDL.Nat,
    'timeframe' : IDL.Text,
    'stochasticOverbought' : IDL.Nat,
    'stochasticDPeriod' : IDL.Nat,
    'macdLongPeriod' : IDL.Nat,
    'rsiOversold' : IDL.Nat,
    'stochasticKPeriod' : IDL.Nat,
    'rsiOverbought' : IDL.Nat,
    'stochasticOversold' : IDL.Nat,
    'macdSignalPeriod' : IDL.Nat,
    'minConfidence' : IDL.Nat,
    'macdShortPeriod' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSignal' : IDL.Func(
        [
          IDL.Text,
          Direction,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getBacktestResults' : IDL.Func([], [IDL.Vec(BacktestResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailySignalCounts' : IDL.Func([], [IDL.Vec(DailyCount)], ['query']),
    'getIndicatorConfig' : IDL.Func([], [IDL.Opt(IndicatorConfig)], ['query']),
    'getSignalsByAsset' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveBacktestResult' : IDL.Func([BacktestResult], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveIndicatorConfig' : IDL.Func([IndicatorConfig], [], []),
    'updateSignalOutcome' : IDL.Func([IDL.Nat, Outcome], [], []),
  });
};

export const init = ({ IDL }) => { return []; };