/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'lossCount' : bigint,
  'perAssetBreakdown' : Array<[string, AssetStats]>,
  'winCount' : bigint,
  'winRate' : bigint,
  'totalSignals' : bigint,
}
export interface AssetStats {
  'wins' : bigint,
  'losses' : bigint,
  'winRate' : bigint,
  'totalSignals' : bigint,
}
export interface BacktestResult {
  'totalTrades' : bigint,
  'endDate' : Time,
  'asset' : string,
  'wins' : bigint,
  'losses' : bigint,
  'winRate' : bigint,
  'maxDrawdown' : number,
  'avgProfit' : number,
  'startDate' : Time,
}
export interface DailyCount { 'date' : string, 'count' : bigint }
export type Direction = { 'buy' : null } |
  { 'sell' : null };
export interface IndicatorConfig {
  'rsiPeriod' : bigint,
  'timeframe' : string,
  'stochasticOverbought' : bigint,
  'stochasticDPeriod' : bigint,
  'macdLongPeriod' : bigint,
  'rsiOversold' : bigint,
  'stochasticKPeriod' : bigint,
  'rsiOverbought' : bigint,
  'stochasticOversold' : bigint,
  'macdSignalPeriod' : bigint,
  'minConfidence' : bigint,
  'macdShortPeriod' : bigint,
}
export type Outcome = { 'win' : null } |
  { 'pending' : null } |
  { 'loss' : null };
export interface Signal {
  'id' : bigint,
  'rsi' : bigint,
  'direction' : Direction,
  'asset' : string,
  'macdValue' : number,
  'timestamp' : Time,
  'expiryMinutes' : bigint,
  'confidence' : bigint,
  'stochasticD' : bigint,
  'stochasticK' : bigint,
  'outcome' : Outcome,
  'macdSignalLine' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSignal' : ActorMethod<
    [string, Direction, bigint, bigint, bigint, bigint, bigint, number, number],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllSignals' : ActorMethod<[], Array<Signal>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getBacktestResults' : ActorMethod<[], Array<BacktestResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailySignalCounts' : ActorMethod<[], Array<DailyCount>>,
  'getIndicatorConfig' : ActorMethod<[], [] | [IndicatorConfig]>,
  'getSignalsByAsset' : ActorMethod<[string], Array<Signal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveBacktestResult' : ActorMethod<[BacktestResult], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveIndicatorConfig' : ActorMethod<[IndicatorConfig], undefined>,
  'updateSignalOutcome' : ActorMethod<[bigint, Outcome], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];