/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    id: bigint;
    rsi: bigint;
    direction: Direction;
    asset: string;
    macdValue: number;
    timestamp: Time;
    expiryMinutes: bigint;
    confidence: bigint;
    stochasticD: bigint;
    stochasticK: bigint;
    outcome: Outcome;
    macdSignalLine: number;
}
export type Time = bigint;
export interface IndicatorConfig {
    rsiPeriod: bigint;
    timeframe: string;
    stochasticOverbought: bigint;
    stochasticDPeriod: bigint;
    macdLongPeriod: bigint;
    rsiOversold: bigint;
    stochasticKPeriod: bigint;
    rsiOverbought: bigint;
    stochasticOversold: bigint;
    macdSignalPeriod: bigint;
    minConfidence: bigint;
    macdShortPeriod: bigint;
}
export interface BacktestResult {
    totalTrades: bigint;
    endDate: Time;
    asset: string;
    wins: bigint;
    losses: bigint;
    winRate: bigint;
    maxDrawdown: number;
    avgProfit: number;
    startDate: Time;
}
export interface Analytics {
    lossCount: bigint;
    perAssetBreakdown: Array<[string, AssetStats]>;
    winCount: bigint;
    winRate: bigint;
    totalSignals: bigint;
}
export interface AssetStats {
    wins: bigint;
    losses: bigint;
    winRate: bigint;
    totalSignals: bigint;
}
export interface UserProfile {
    name: string;
}
export interface DailyCount {
    date: string;
    count: bigint;
}
export enum Direction {
    buy = "buy",
    sell = "sell"
}
export enum Outcome {
    win = "win",
    pending = "pending",
    loss = "loss"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSignal(asset: string, direction: Direction, confidence: bigint, expiryMinutes: bigint, rsi: bigint, stochasticK: bigint, stochasticD: bigint, macdValue: number, macdSignalLine: number): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllSignals(): Promise<Array<Signal>>;
    getAnalytics(): Promise<Analytics>;
    getBacktestResults(): Promise<Array<BacktestResult>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailySignalCounts(): Promise<Array<DailyCount>>;
    getIndicatorConfig(): Promise<IndicatorConfig | null>;
    getSignalsByAsset(asset: string): Promise<Array<Signal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveBacktestResult(result: BacktestResult): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveIndicatorConfig(config: IndicatorConfig): Promise<void>;
    updateSignalOutcome(id: bigint, outcome: Outcome): Promise<void>;
}
import type { Direction as _Direction, IndicatorConfig as _IndicatorConfig, Outcome as _Outcome, Signal as _Signal, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSignal(arg0: string, arg1: Direction, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: number, arg8: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSignal(arg0, to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSignal(arg0, to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSignals();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSignals();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getBacktestResults(): Promise<Array<BacktestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBacktestResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBacktestResults();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailySignalCounts(): Promise<Array<DailyCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySignalCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySignalCounts();
            return result;
        }
    }
    async getIndicatorConfig(): Promise<IndicatorConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIndicatorConfig();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIndicatorConfig();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignalsByAsset(arg0: string): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalsByAsset(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalsByAsset(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveBacktestResult(arg0: BacktestResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBacktestResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBacktestResult(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveIndicatorConfig(arg0: IndicatorConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIndicatorConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIndicatorConfig(arg0);
            return result;
        }
    }
    async updateSignalOutcome(arg0: bigint, arg1: Outcome): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignalOutcome(arg0, to_candid_Outcome_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignalOutcome(arg0, to_candid_Outcome_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Direction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Outcome_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Outcome): Outcome {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IndicatorConfig]): IndicatorConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    rsi: bigint;
    direction: _Direction;
    asset: string;
    macdValue: number;
    timestamp: _Time;
    expiryMinutes: bigint;
    confidence: bigint;
    stochasticD: bigint;
    stochasticK: bigint;
    outcome: _Outcome;
    macdSignalLine: number;
}): {
    id: bigint;
    rsi: bigint;
    direction: Direction;
    asset: string;
    macdValue: number;
    timestamp: Time;
    expiryMinutes: bigint;
    confidence: bigint;
    stochasticD: bigint;
    stochasticK: bigint;
    outcome: Outcome;
    macdSignalLine: number;
} {
    return {
        id: value.id,
        rsi: value.rsi,
        direction: from_candid_Direction_n8(_uploadFile, _downloadFile, value.direction),
        asset: value.asset,
        macdValue: value.macdValue,
        timestamp: value.timestamp,
        expiryMinutes: value.expiryMinutes,
        confidence: value.confidence,
        stochasticD: value.stochasticD,
        stochasticK: value.stochasticK,
        outcome: from_candid_Outcome_n10(_uploadFile, _downloadFile, value.outcome),
        macdSignalLine: value.macdSignalLine
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    win: null;
} | {
    pending: null;
} | {
    loss: null;
}): Outcome {
    return "win" in value ? Outcome.win : "pending" in value ? Outcome.pending : "loss" in value ? Outcome.loss : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Direction {
    return "buy" in value ? Direction.buy : "sell" in value ? Direction.sell : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Signal>): Array<Signal> {
    return value.map((x)=>from_candid_Signal_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Direction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Outcome_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): _Outcome {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): {
    win: null;
} | {
    pending: null;
} | {
    loss: null;
} {
    return value == Outcome.win ? {
        win: null
    } : value == Outcome.pending ? {
        pending: null
    } : value == Outcome.loss ? {
        loss: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    buy: null;
} | {
    sell: null;
} {
    return value == Direction.buy ? {
        buy: null
    } : value == Direction.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
